insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (30, 'LUNCH', 'Lasagna', 'Recept',45 ,45, 75, 650);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (5, 'BREAKFAST', 'Granola, Greek Yogurt and Brazil Nuts', '75g/2.65oz Granola, 100g/3.5oz Greek Yogurt, Topping: 28g/1oz chopped Brazil Nuts, 1 handful each of Blueberries and Raspberries',75 ,40, 35, 722);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (5, 'SNACK', 'Oatcakes with Peanut Butter and Nectarine', '2 Oatcakes (oat crackers), 1 tablespoon Peanut Butter, 1 Nectarine',12 ,24, 33, 246);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (5, 'LUNCH', 'Roasted chicke with spinacci and Avocado', '2 Whole pita Breads, 100g Roast Chicken, 1 medium Avocado and Large Handful of Spinach, Watercress and Rocket',82 ,66, 35, 844);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (0, 'SNACK', 'Trail Mix', '50g of Trail Mix',20 ,30, 0, 250);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (5, 'DINNER', 'Salomon Fillets', 'Recipe to be added',50 ,70, 20, 929);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (0, 'SNACK', 'Banana', 'Medium Banana',0 ,15, 25, 105);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (0, 'LUNCH', 'Spaghetti with Feta, Spinach & Shrimp', 'Spaghetti 100g, Fresh Spinach 150g, Garlic Cloves 5g, Olive oil 10ml, Feta 25g, Shrimp 50g', 31 , 21, 63 , 596);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (0, 'LUNCH', 'Fried Potato Breakfast with Bacon & Eggs, Spinach & Shrimp', 'Spaghetti 100g, Fresh Spinach 150g, Garlic Cloves 5g, Olive oil 10ml, Feta 25g, Shrimp 50g', 35 , 50, 25 , 627);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (0, 'LUNCH', 'Mushroom Omelet', 'TBA', 20, 35, 15 , 389);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (0, 'BREAKFAST', 'Protein Breakfast Muffins', 'TBA', 10 , 5, 5 , 41);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (15, 'BREAKFAST', 'Ham & Spinach Scrambled Eggs', 'TBA', 25 , 15, 15 , 230);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (0, 'BREAKFAST', 'Savory Zucchini Pancakes', 'TBA', 40 , 20, 35 , 529);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (0, 'LUNCH', 'Basic Fried Potato', 'TBA', 30 , 40, 15 , 302);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (0, 'DINNER', 'Tomato Omelet with Feta', 'TBA', 30 , 40, 15 , 312);
insert into meals(junk_percentage, meal_type, name, recipe, proteins, fats, carbon_hydrates, k_cal) values (0, 'DINNER', 'Egg & Spinach Tartlets', 'TBA', 10 , 15 , 5 , 163);


insert into health_issue_types(meal_id, health_issue_types) values (1, 'DIABETES');
insert into health_issue_types(meal_id, health_issue_types) values (1, 'HEART_PROBLEMS');
insert into health_issue_types(meal_id, health_issue_types) values (2, 'HIGH_FAT');
insert into health_issue_types(meal_id, health_issue_types) values (3, 'HIGH_FAT');
insert into health_issue_types(meal_id, health_issue_types) values (7, 'DIABETES');


insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba1', 'HIGH', true, 'MASS_GAIN', 'Vezba1');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba2', 'HIGH', true, 'MASS_GAIN', 'Vezba2');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba3', 'LOW', true, 'WEIGHT_LOSS', 'Vezba3');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba4', 'MEDIUM', false, 'MASS_GAIN', 'Vezba4');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba5', 'HIGH', true, 'MASS_GAIN', 'Vezba5');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba6', 'HIGH', false, 'MASS_GAIN', 'Vezba6');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba7', 'HIGH', true, 'MASS_GAIN', 'Vezba7');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba8', 'LOW', false, 'WEIGHT_LOSS', 'Vezba8');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba9', 'MEDIUM', false, 'MASS_GAIN', 'Vezba9');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba10', 'HIGH', true, 'MASS_GAIN', 'Vezba10');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba11', 'LOW', true, 'WEIGHT_LOSS', 'Vezba11');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba12', 'HIGH', false, 'MASS_GAIN', 'Vezba12');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba13', 'LOW', true, 'WEIGHT_LOSS', 'Vezba13');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba14', 'MEDIUM', false, 'MASS_GAIN', 'Vezba14');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba15', 'HIGH', true, 'MASS_GAIN', 'Vezba15');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba16', 'LOW', true, 'MASS_GAIN', 'Vezba16');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba17', 'HIGH', false, 'MASS_GAIN', 'Vezba17');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba18', 'LOW', true, 'WEIGHT_LOSS', 'Vezba18');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba19', 'MEDIUM', false, 'MASS_GAIN', 'Vezba19');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba20', 'HIGH', true, 'MASS_GAIN', 'Vezba20');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba21', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba21');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba22', 'HIGH', true, 'MASS_GAIN', 'Vezba22');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba23', 'LOW', true, 'WEIGHT_LOSS', 'Vezba23');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba24', 'MEDIUM', false, 'MASS_GAIN', 'Vezba24');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba25', 'HIGH', true, 'MASS_GAIN', 'Vezba25');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba26', 'HIGH', false, 'MASS_GAIN', 'Vezba26');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba27', 'LOW', true, 'WEIGHT_LOSS', 'Vezba27');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba28', 'HIGH', true, 'MASS_GAIN', 'Vezba28');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba29', 'HIGH', false, 'MASS_GAIN', 'Vezba29');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba30', 'MEDIUM', true, 'MASS_GAIN', 'Vezba30');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba31', 'LOW', true, 'WEIGHT_LOSS', 'Vezba31');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba32', 'HIGH', false, 'WEIGHT_LOSS', 'Vezba32');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba33', 'MEDIUM', true, 'WEIGHT_LOSS', 'Vezba33');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba34', 'LOW', false, 'WEIGHT_LOSS', 'Vezba34');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba35', 'HIGH', true, 'WEIGHT_LOSS', 'Vezba35');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba36', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba36');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba37', 'LOW', true, 'WEIGHT_LOSS', 'Vezba37');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba38', 'HIGH', false, 'WEIGHT_LOSS', 'Vezba38');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba39', 'MEDIUM', true, 'WEIGHT_LOSS', 'Vezba39');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba40', 'LOW', false, 'WEIGHT_LOSS', 'Vezba40');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba41', 'HIGH', true, 'WEIGHT_LOSS', 'Vezba41');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba42', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba42');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba43', 'HIGH', true, 'WEIGHT_LOSS', 'Vezba43');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba44', 'LOW', false, 'WEIGHT_LOSS', 'Vezba44');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba45', 'LOW', true, 'WEIGHT_LOSS', 'Vezba45');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba46', 'HIGH', false, 'WEIGHT_LOSS', 'Vezba46');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba47', 'MEDIUM', true, 'WEIGHT_LOSS', 'Vezba47');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba48', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba48');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba49', 'LOW', true, 'WEIGHT_LOSS', 'Vezba49');



insert into muscles_exercise(exercise_id, muscle_list) values (1, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (1, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (2, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (3, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (4, 'HAMSTRINGS');
insert into muscles_exercise(exercise_id, muscle_list) values (4, 'GLUTES');
insert into muscles_exercise(exercise_id, muscle_list) values (4, 'FOREARMS');
insert into muscles_exercise(exercise_id, muscle_list) values (4, 'TRAPEZIUS');
insert into muscles_exercise(exercise_id, muscle_list) values (5, 'LATS');
insert into muscles_exercise(exercise_id, muscle_list) values (5, 'ABDOMINALS');
insert into muscles_exercise(exercise_id, muscle_list) values (6, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (7, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (8, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (8, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (9, 'HAMSTRINGS');
insert into muscles_exercise(exercise_id, muscle_list) values (9, 'GLUTES');
insert into muscles_exercise(exercise_id, muscle_list) values (9, 'FOREARMS');
insert into muscles_exercise(exercise_id, muscle_list) values (9, 'TRAPEZIUS');
insert into muscles_exercise(exercise_id, muscle_list) values (10, 'LATS');
insert into muscles_exercise(exercise_id, muscle_list) values (10, 'ABDOMINALS');
insert into muscles_exercise(exercise_id, muscle_list) values (10, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (10, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (11, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (12, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (13, 'HAMSTRINGS');
insert into muscles_exercise(exercise_id, muscle_list) values (14, 'GLUTES');
insert into muscles_exercise(exercise_id, muscle_list) values (15, 'FOREARMS');
insert into muscles_exercise(exercise_id, muscle_list) values (16, 'TRAPEZIUS');
insert into muscles_exercise(exercise_id, muscle_list) values (16, 'LATS');
insert into muscles_exercise(exercise_id, muscle_list) values (17, 'ABDOMINALS');
insert into muscles_exercise(exercise_id, muscle_list) values (17, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (17, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (18, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (19, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (20, 'HAMSTRINGS');
insert into muscles_exercise(exercise_id, muscle_list) values (20, 'GLUTES');
insert into muscles_exercise(exercise_id, muscle_list) values (20, 'FOREARMS');
insert into muscles_exercise(exercise_id, muscle_list) values (21, 'TRAPEZIUS');
insert into muscles_exercise(exercise_id, muscle_list) values (22, 'LATS');
insert into muscles_exercise(exercise_id, muscle_list) values (22, 'ABDOMINALS');
insert into muscles_exercise(exercise_id, muscle_list) values (22, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (23, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (23, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (23, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (24, 'HAMSTRINGS');
insert into muscles_exercise(exercise_id, muscle_list) values (24, 'GLUTES');
insert into muscles_exercise(exercise_id, muscle_list) values (24, 'FOREARMS');
insert into muscles_exercise(exercise_id, muscle_list) values (25, 'TRAPEZIUS');
insert into muscles_exercise(exercise_id, muscle_list) values (26, 'LATS');
insert into muscles_exercise(exercise_id, muscle_list) values (26, 'ABDOMINALS');
insert into muscles_exercise(exercise_id, muscle_list) values (26, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (26, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (26, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (27, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (27, 'HAMSTRINGS');
insert into muscles_exercise(exercise_id, muscle_list) values (27, 'GLUTES');
insert into muscles_exercise(exercise_id, muscle_list) values (28, 'FOREARMS');
insert into muscles_exercise(exercise_id, muscle_list) values (29, 'TRAPEZIUS');
insert into muscles_exercise(exercise_id, muscle_list) values (29, 'LATS');
insert into muscles_exercise(exercise_id, muscle_list) values (29, 'ABDOMINALS');
insert into muscles_exercise(exercise_id, muscle_list) values (29, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (30, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (30, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (30, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (30, 'HAMSTRINGS');


insert into administrators (id, first_name, last_name, username, password, verified, age) values (nextval('person_seq'), 'Milorad', 'Radovic', 'micoadmin', '$2y$12$NFN7DJUX1lFfaDX1tc9/6uBtgls9SZOU9iwjhrlXJc0xr471vgKAK', true, 45);
insert into administrators (id, first_name, last_name, username, password, verified, age) values (nextval('person_seq'), 'Vukasin', 'Ocokoljic', 'vukiadmin', '$2y$12$NFN7DJUX1lFfaDX1tc9/6uBtgls9SZOU9iwjhrlXJc0xr471vgKAK', true, 55);


insert into users (id, first_name, last_name, username, password, verified, age) values (nextval('person_seq'), 'Milorad', 'Radovic', 'micouser', '$2y$12$NFN7DJUX1lFfaDX1tc9/6uBtgls9SZOU9iwjhrlXJc0xr471vgKAK', true, 25);
insert into users (id, first_name, last_name, username, password, verified, age) values (nextval('person_seq'), 'Vukasin', 'Ocokoljic', 'vukiuser', '$2y$12$NFN7DJUX1lFfaDX1tc9/6uBtgls9SZOU9iwjhrlXJc0xr471vgKAK', true, 35);


insert into authorities (name) values ('ROLE_ADMINISTRATOR');
insert into authorities (name) values ('ROLE_USER');


insert into user_authority (user_id, authority_id) values (1, 1);
insert into user_authority (user_id, authority_id) values (2, 1);
insert into user_authority (user_id, authority_id) values (3, 2);
insert into user_authority (user_id, authority_id) values (4, 2);