insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba1', 'HIGH', true, 'MASS_GAIN', 'Vezba1');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba2', 'HIGH', true, 'MASS_GAIN', 'Vezba2');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba3', 'LOW', true, 'WEIGHT_LOSS', 'Vezba3');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba4', 'MEDIUM', false, 'MASS_GAIN', 'Vezba4');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba5', 'HIGH', true, 'MASS_GAIN', 'Vezba5');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba6', 'HIGH', false, 'MASS_GAIN', 'Vezba6');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba7', 'HIGH', true, 'MASS_GAIN', 'Vezba7');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba8', 'LOW', false, 'WEIGHT_LOSS', 'Vezba8');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba9', 'MEDIUM', false, 'MASS_GAIN', 'Vezba9');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba10', 'HIGH', true, 'MASS_GAIN', 'Vezba10');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba11', 'LOW', true, 'WEIGHT_LOSS', 'Vezba11');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba12', 'HIGH', false, 'MASS_GAIN', 'Vezba12');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba13', 'LOW', true, 'WEIGHT_LOSS', 'Vezba13');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba14', 'MEDIUM', false, 'MASS_GAIN', 'Vezba14');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba15', 'HIGH', true, 'MASS_GAIN', 'Vezba15');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba16', 'LOW', true, 'MASS_GAIN', 'Vezba16');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba17', 'HIGH', false, 'MASS_GAIN', 'Vezba17');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba18', 'LOW', true, 'WEIGHT_LOSS', 'Vezba18');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba19', 'MEDIUM', false, 'MASS_GAIN', 'Vezba19');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba20', 'HIGH', true, 'MASS_GAIN', 'Vezba20');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba21', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba21');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba22', 'HIGH', true, 'MASS_GAIN', 'Vezba22');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba23', 'LOW', true, 'WEIGHT_LOSS', 'Vezba23');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba24', 'MEDIUM', false, 'MASS_GAIN', 'Vezba24');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba25', 'HIGH', true, 'MASS_GAIN', 'Vezba25');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba26', 'HIGH', false, 'MASS_GAIN', 'Vezba26');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba27', 'LOW', true, 'WEIGHT_LOSS', 'Vezba27');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba28', 'HIGH', true, 'MASS_GAIN', 'Vezba28');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba29', 'HIGH', false, 'MASS_GAIN', 'Vezba29');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba30', 'MEDIUM', true, 'MASS_GAIN', 'Vezba30');

insert into muscles(exercise_id, muscle_list) values (1, 'BICEPS');
    insert into muscles(exercise_id, muscle_list) values (1, 'TRICEPS');
insert into muscles(exercise_id, muscle_list) values (2, 'QUADRICEPS');
insert into muscles(exercise_id, muscle_list) values (3, 'CALVES');
insert into muscles(exercise_id, muscle_list) values (4, 'HAMSTRINGS');
insert into muscles(exercise_id, muscle_list) values (4, 'GLUTES');
insert into muscles(exercise_id, muscle_list) values (4, 'FOREARMS');
insert into muscles(exercise_id, muscle_list) values (4, 'TRAPEZIUS');
insert into muscles(exercise_id, muscle_list) values (5, 'LATS');
insert into muscles(exercise_id, muscle_list) values (5, 'ABDOMINALS');
insert into muscles(exercise_id, muscle_list) values (6, 'BICEPS');
insert into muscles(exercise_id, muscle_list) values (7, 'TRICEPS');
insert into muscles(exercise_id, muscle_list) values (8, 'QUADRICEPS');
insert into muscles(exercise_id, muscle_list) values (8, 'CALVES');
insert into muscles(exercise_id, muscle_list) values (9, 'HAMSTRINGS');
insert into muscles(exercise_id, muscle_list) values (9, 'GLUTES');
insert into muscles(exercise_id, muscle_list) values (9, 'FOREARMS');
insert into muscles(exercise_id, muscle_list) values (9, 'TRAPEZIUS');
insert into muscles(exercise_id, muscle_list) values (10, 'LATS');
insert into muscles(exercise_id, muscle_list) values (10, 'ABDOMINALS');
insert into muscles(exercise_id, muscle_list) values (10, 'BICEPS');
insert into muscles(exercise_id, muscle_list) values (10, 'TRICEPS');
insert into muscles(exercise_id, muscle_list) values (11, 'QUADRICEPS');
insert into muscles(exercise_id, muscle_list) values (12, 'CALVES');
insert into muscles(exercise_id, muscle_list) values (13, 'HAMSTRINGS');
insert into muscles(exercise_id, muscle_list) values (14, 'GLUTES');
insert into muscles(exercise_id, muscle_list) values (15, 'FOREARMS');
insert into muscles(exercise_id, muscle_list) values (16, 'TRAPEZIUS');
insert into muscles(exercise_id, muscle_list) values (16, 'LATS');
insert into muscles(exercise_id, muscle_list) values (17, 'ABDOMINALS');
insert into muscles(exercise_id, muscle_list) values (17, 'BICEPS');
insert into muscles(exercise_id, muscle_list) values (17, 'TRICEPS');
insert into muscles(exercise_id, muscle_list) values (18, 'QUADRICEPS');
insert into muscles(exercise_id, muscle_list) values (19, 'CALVES');
insert into muscles(exercise_id, muscle_list) values (20, 'HAMSTRINGS');
insert into muscles(exercise_id, muscle_list) values (20, 'GLUTES');
insert into muscles(exercise_id, muscle_list) values (20, 'FOREARMS');
insert into muscles(exercise_id, muscle_list) values (21, 'TRAPEZIUS');
insert into muscles(exercise_id, muscle_list) values (22, 'LATS');
insert into muscles(exercise_id, muscle_list) values (22, 'ABDOMINALS');
insert into muscles(exercise_id, muscle_list) values (22, 'BICEPS');
insert into muscles(exercise_id, muscle_list) values (23, 'TRICEPS');
insert into muscles(exercise_id, muscle_list) values (23, 'QUADRICEPS');
insert into muscles(exercise_id, muscle_list) values (23, 'CALVES');
insert into muscles(exercise_id, muscle_list) values (24, 'HAMSTRINGS');
insert into muscles(exercise_id, muscle_list) values (24, 'GLUTES');
insert into muscles(exercise_id, muscle_list) values (24, 'FOREARMS');
insert into muscles(exercise_id, muscle_list) values (25, 'TRAPEZIUS');
insert into muscles(exercise_id, muscle_list) values (26, 'LATS');
insert into muscles(exercise_id, muscle_list) values (26, 'ABDOMINALS');
insert into muscles(exercise_id, muscle_list) values (26, 'BICEPS');
insert into muscles(exercise_id, muscle_list) values (26, 'TRICEPS');
insert into muscles(exercise_id, muscle_list) values (26, 'QUADRICEPS');
insert into muscles(exercise_id, muscle_list) values (27, 'CALVES');
insert into muscles(exercise_id, muscle_list) values (27, 'HAMSTRINGS');
insert into muscles(exercise_id, muscle_list) values (27, 'GLUTES');
insert into muscles(exercise_id, muscle_list) values (28, 'FOREARMS');
insert into muscles(exercise_id, muscle_list) values (29, 'TRAPEZIUS');
insert into muscles(exercise_id, muscle_list) values (29, 'LATS');
insert into muscles(exercise_id, muscle_list) values (29, 'ABDOMINALS');
insert into muscles(exercise_id, muscle_list) values (29, 'BICEPS');
insert into muscles(exercise_id, muscle_list) values (30, 'TRICEPS');
insert into muscles(exercise_id, muscle_list) values (30, 'QUADRICEPS');
insert into muscles(exercise_id, muscle_list) values (30, 'CALVES');
insert into muscles(exercise_id, muscle_list) values (30, 'HAMSTRINGS');