insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba1', 'HIGH', true, 'MASS_GAIN', 'Vezba1');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba2', 'HIGH', true, 'MASS_GAIN', 'Vezba2');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba3', 'LOW', true, 'WEIGHT_LOSS', 'Vezba3');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba4', 'MEDIUM', false, 'MASS_GAIN', 'Vezba4');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba5', 'HIGH', true, 'MASS_GAIN', 'Vezba5');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba6', 'HIGH', false, 'MASS_GAIN', 'Vezba6');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba7', 'HIGH', true, 'MASS_GAIN', 'Vezba7');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba8', 'LOW', false, 'WEIGHT_LOSS', 'Vezba8');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba9', 'MEDIUM', false, 'MASS_GAIN', 'Vezba9');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba10', 'HIGH', true, 'MASS_GAIN', 'Vezba10');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba11', 'LOW', true, 'WEIGHT_LOSS', 'Vezba11');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba12', 'HIGH', false, 'MASS_GAIN', 'Vezba12');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba13', 'LOW', true, 'WEIGHT_LOSS', 'Vezba13');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba14', 'MEDIUM', false, 'MASS_GAIN', 'Vezba14');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba15', 'HIGH', true, 'MASS_GAIN', 'Vezba15');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba16', 'LOW', true, 'MASS_GAIN', 'Vezba16');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba17', 'HIGH', false, 'MASS_GAIN', 'Vezba17');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba18', 'LOW', true, 'WEIGHT_LOSS', 'Vezba18');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba19', 'MEDIUM', false, 'MASS_GAIN', 'Vezba19');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba20', 'HIGH', true, 'MASS_GAIN', 'Vezba20');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba21', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba21');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba22', 'HIGH', true, 'MASS_GAIN', 'Vezba22');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba23', 'LOW', true, 'WEIGHT_LOSS', 'Vezba23');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba24', 'MEDIUM', false, 'MASS_GAIN', 'Vezba24');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba25', 'HIGH', true, 'MASS_GAIN', 'Vezba25');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba26', 'HIGH', false, 'MASS_GAIN', 'Vezba26');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba27', 'LOW', true, 'WEIGHT_LOSS', 'Vezba27');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba28', 'HIGH', true, 'MASS_GAIN', 'Vezba28');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba29', 'HIGH', false, 'MASS_GAIN', 'Vezba29');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba30', 'MEDIUM', true, 'MASS_GAIN', 'Vezba30');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba31', 'LOW', true, 'WEIGHT_LOSS', 'Vezba31');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba32', 'HIGH', false, 'WEIGHT_LOSS', 'Vezba32');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba33', 'MEDIUM', true, 'WEIGHT_LOSS', 'Vezba33');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba34', 'LOW', false, 'WEIGHT_LOSS', 'Vezba34');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba35', 'HIGH', true, 'WEIGHT_LOSS', 'Vezba35');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba36', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba36');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba37', 'LOW', true, 'WEIGHT_LOSS', 'Vezba37');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba38', 'HIGH', false, 'WEIGHT_LOSS', 'Vezba38');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba39', 'MEDIUM', true, 'WEIGHT_LOSS', 'Vezba39');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba40', 'LOW', false, 'WEIGHT_LOSS', 'Vezba40');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba41', 'HIGH', true, 'WEIGHT_LOSS', 'Vezba41');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba42', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba42');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba43', 'HIGH', true, 'WEIGHT_LOSS', 'Vezba43');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba44', 'LOW', false, 'WEIGHT_LOSS', 'Vezba44');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba45', 'LOW', true, 'WEIGHT_LOSS', 'Vezba45');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba46', 'HIGH', false, 'WEIGHT_LOSS', 'Vezba46');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba47', 'MEDIUM', true, 'WEIGHT_LOSS', 'Vezba47');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba48', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba48');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba49', 'LOW', true, 'WEIGHT_LOSS', 'Vezba49');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba51', 'MEDIUM', true, 'MASS_GAIN', 'Vezba51');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba52', 'MEDIUM', true, 'MASS_GAIN', 'Vezba52');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba53', 'MEDIUM', true, 'MASS_GAIN', 'Vezba53');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba54', 'MEDIUM', true, 'MASS_GAIN', 'Vezba54');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba55', 'MEDIUM', true, 'MASS_GAIN', 'Vezba55');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba56', 'MEDIUM', true, 'MASS_GAIN', 'Vezba56');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba57', 'MEDIUM', true, 'MASS_GAIN', 'Vezba57');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba58', 'MEDIUM', true, 'MASS_GAIN', 'Vezba58');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba59', 'MEDIUM', true, 'MASS_GAIN', 'Vezba59');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba60', 'MEDIUM', true, 'MASS_GAIN', 'Vezba60');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba61', 'HIGH', true, 'MASS_GAIN', 'Vezba61');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba62', 'HIGH', true, 'MASS_GAIN', 'Vezba62');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba63', 'HIGH', true, 'MASS_GAIN', 'Vezba63');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba64', 'HIGH', true, 'MASS_GAIN', 'Vezba64');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba65', 'HIGH', true, 'MASS_GAIN', 'Vezba65');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba66', 'HIGH', true, 'MASS_GAIN', 'Vezba66');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba67', 'HIGH', true, 'MASS_GAIN', 'Vezba67');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba68', 'HIGH', true, 'MASS_GAIN', 'Vezba68');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba69', 'HIGH', true, 'MASS_GAIN', 'Vezba69');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba70', 'HIGH', true, 'MASS_GAIN', 'Vezba70');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba71', 'LOW', true, 'MASS_GAIN', 'Vezba71');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba72', 'LOW', true, 'MASS_GAIN', 'Vezba72');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba73', 'LOW', true, 'MASS_GAIN', 'Vezba73');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba74', 'LOW', true, 'MASS_GAIN', 'Vezba74');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba75', 'LOW', true, 'MASS_GAIN', 'Vezba75');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba76', 'LOW', true, 'MASS_GAIN', 'Vezba76');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba77', 'LOW', true, 'MASS_GAIN', 'Vezba77');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba78', 'LOW', true, 'MASS_GAIN', 'Vezba78');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba79', 'LOW', true, 'MASS_GAIN', 'Vezba79');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba80', 'LOW', true, 'MASS_GAIN', 'Vezba80');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba81', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba81');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba82', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba82');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba83', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba83');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba84', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba84');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba85', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba85');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba86', 'MEDIUM', false, 'WEIGHT_LOSS', 'Vezba86');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba87', 'MEDIUM', true, 'MASS_GAIN', 'Vezba87');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba88', 'MEDIUM', true, 'MASS_GAIN', 'Vezba88');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba89', 'MEDIUM', true, 'MASS_GAIN', 'Vezba89');
insert into exercises (description, difficulty, equipment, exercise_category, name) values ('Vezba90', 'MEDIUM', true, 'MASS_GAIN', 'Vezba90');


insert into muscles_exercise(exercise_id, muscle_list) values (1, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (1, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (2, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (3, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (4, 'HAMSTRINGS');
insert into muscles_exercise(exercise_id, muscle_list) values (4, 'GLUTES');
insert into muscles_exercise(exercise_id, muscle_list) values (4, 'FOREARMS');
insert into muscles_exercise(exercise_id, muscle_list) values (4, 'TRAPEZIUS');
insert into muscles_exercise(exercise_id, muscle_list) values (5, 'LATS');
insert into muscles_exercise(exercise_id, muscle_list) values (5, 'ABDOMINALS');
insert into muscles_exercise(exercise_id, muscle_list) values (6, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (7, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (8, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (8, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (9, 'HAMSTRINGS');
insert into muscles_exercise(exercise_id, muscle_list) values (9, 'GLUTES');
insert into muscles_exercise(exercise_id, muscle_list) values (9, 'FOREARMS');
insert into muscles_exercise(exercise_id, muscle_list) values (9, 'TRAPEZIUS');
insert into muscles_exercise(exercise_id, muscle_list) values (10, 'LATS');
insert into muscles_exercise(exercise_id, muscle_list) values (10, 'ABDOMINALS');
insert into muscles_exercise(exercise_id, muscle_list) values (10, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (10, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (11, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (12, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (13, 'HAMSTRINGS');
insert into muscles_exercise(exercise_id, muscle_list) values (14, 'GLUTES');
insert into muscles_exercise(exercise_id, muscle_list) values (15, 'FOREARMS');
insert into muscles_exercise(exercise_id, muscle_list) values (16, 'TRAPEZIUS');
insert into muscles_exercise(exercise_id, muscle_list) values (16, 'LATS');
insert into muscles_exercise(exercise_id, muscle_list) values (17, 'ABDOMINALS');
insert into muscles_exercise(exercise_id, muscle_list) values (17, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (17, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (18, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (19, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (20, 'HAMSTRINGS');
insert into muscles_exercise(exercise_id, muscle_list) values (20, 'GLUTES');
insert into muscles_exercise(exercise_id, muscle_list) values (20, 'FOREARMS');
insert into muscles_exercise(exercise_id, muscle_list) values (21, 'TRAPEZIUS');
insert into muscles_exercise(exercise_id, muscle_list) values (22, 'LATS');
insert into muscles_exercise(exercise_id, muscle_list) values (22, 'ABDOMINALS');
insert into muscles_exercise(exercise_id, muscle_list) values (22, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (23, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (23, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (23, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (24, 'HAMSTRINGS');
insert into muscles_exercise(exercise_id, muscle_list) values (24, 'GLUTES');
insert into muscles_exercise(exercise_id, muscle_list) values (24, 'FOREARMS');
insert into muscles_exercise(exercise_id, muscle_list) values (25, 'TRAPEZIUS');
insert into muscles_exercise(exercise_id, muscle_list) values (26, 'LATS');
insert into muscles_exercise(exercise_id, muscle_list) values (26, 'ABDOMINALS');
insert into muscles_exercise(exercise_id, muscle_list) values (26, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (26, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (26, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (27, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (27, 'HAMSTRINGS');
insert into muscles_exercise(exercise_id, muscle_list) values (27, 'GLUTES');
insert into muscles_exercise(exercise_id, muscle_list) values (28, 'FOREARMS');
insert into muscles_exercise(exercise_id, muscle_list) values (29, 'TRAPEZIUS');
insert into muscles_exercise(exercise_id, muscle_list) values (29, 'LATS');
insert into muscles_exercise(exercise_id, muscle_list) values (29, 'ABDOMINALS');
insert into muscles_exercise(exercise_id, muscle_list) values (29, 'BICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (30, 'TRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (30, 'QUADRICEPS');
insert into muscles_exercise(exercise_id, muscle_list) values (30, 'CALVES');
insert into muscles_exercise(exercise_id, muscle_list) values (30, 'HAMSTRINGS');
